on:
  workflow_run:
    workflows: [Update Lambda Code & Configuration]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

name: API Tests

jobs:
  run_api_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      RECEIVE_BOX: ${{ secrets.RECEIVE_BOX }}
      RECEIVE_CODE: ${{ secrets.RECEIVE_CODE }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Testing Packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run Send Test
        run: python test/test_send.py --sender Dumfing
      - name: Run Receive Test
        run: python test/test_receive.py
      - name: Run Acknowledge Test
        run: python test/test_acknowledge.py

